// Code generated by mockery v2.35.3. DO NOT EDIT.

package server

import (
	context "context"
	slog "log/slog"

	mock "github.com/stretchr/testify/mock"
)

// MockWorkerTaskFunc is an autogenerated mock type for the WorkerTaskFunc type
type MockWorkerTaskFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, logger
func (_m *MockWorkerTaskFunc) Execute(ctx context.Context, logger *slog.Logger) error {
	ret := _m.Called(ctx, logger)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *slog.Logger) error); ok {
		r0 = rf(ctx, logger)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockWorkerTaskFunc creates a new instance of MockWorkerTaskFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkerTaskFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkerTaskFunc {
	mock := &MockWorkerTaskFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
