// Code generated by mockery v2.35.3. DO NOT EDIT.

package cmd

import (
	mock "github.com/stretchr/testify/mock"
	server "github.com/tscolari/servicetools/server"
)

// MockHasWorker is an autogenerated mock type for the HasWorker type
type MockHasWorker struct {
	mock.Mock
}

// ConfigureWorker provides a mock function with given fields: _a0
func (_m *MockHasWorker) ConfigureWorker(_a0 *server.WithWorker) {
	_m.Called(_a0)
}

// NewMockHasWorker creates a new instance of MockHasWorker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHasWorker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHasWorker {
	mock := &MockHasWorker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
