// Code generated by mockery v2.35.3. DO NOT EDIT.

package cmd

import (
	mock "github.com/stretchr/testify/mock"
	server "github.com/tscolari/servicetools/server"
)

// MockHasHTTP is an autogenerated mock type for the HasHTTP type
type MockHasHTTP struct {
	mock.Mock
}

// ConfigureHTTP provides a mock function with given fields: _a0
func (_m *MockHasHTTP) ConfigureHTTP(_a0 *server.WithHTTP) {
	_m.Called(_a0)
}

// NewMockHasHTTP creates a new instance of MockHasHTTP. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHasHTTP(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHasHTTP {
	mock := &MockHasHTTP{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
