// Code generated by mockery v2.35.3. DO NOT EDIT.

package cmd

import (
	mock "github.com/stretchr/testify/mock"
	server "github.com/tscolari/servicetools/server"
)

// MockHasMetrics is an autogenerated mock type for the HasMetrics type
type MockHasMetrics struct {
	mock.Mock
}

// ConfigureMetrics provides a mock function with given fields: _a0
func (_m *MockHasMetrics) ConfigureMetrics(_a0 *server.WithMetrics) {
	_m.Called(_a0)
}

// NewMockHasMetrics creates a new instance of MockHasMetrics. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHasMetrics(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHasMetrics {
	mock := &MockHasMetrics{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
