// Code generated by mockery v2.35.3. DO NOT EDIT.

package cmd

import (
	mock "github.com/stretchr/testify/mock"
	server "github.com/tscolari/servicetools/server"
)

// MockHasReaderDatabase is an autogenerated mock type for the HasReaderDatabase type
type MockHasReaderDatabase struct {
	mock.Mock
}

// ConfigureReaderDatabase provides a mock function with given fields: _a0
func (_m *MockHasReaderDatabase) ConfigureReaderDatabase(_a0 *server.WithRDB) {
	_m.Called(_a0)
}

// NewMockHasReaderDatabase creates a new instance of MockHasReaderDatabase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHasReaderDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHasReaderDatabase {
	mock := &MockHasReaderDatabase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
